spring:
  application:
    name: kill-batch-system

  sql:
    init:
      mode: always
      schema-locations: classpath:org/springframework/batch/core/schema-drop-postgresql.sql

  batch:
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: password

  data:
    mongodb:
      database: cyberops

    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.batch.item.database: DEBUG